### ISSUE TITLE
I can create an user without a password

### ISSUE THREAD

**Issue by Merentie** [lamtonylam/tsoha2024#2]
When registering I can create an account while the password field is empty

**Comment by lamtonylam** [comment]
Hi @Merentie ! Thank you for your contribution and reporting this bug, I'll investigate it and fix it ASAP.

**Comment by lamtonylam** [comment]
Fixed in commit cfe7d92.
Thank you again for raising this issue.
I am closing this issue for now. If you encounter further issues, please open this issue again.
@Merentie
